AWSTemplateFormatVersion: '2010-09-09'

Resources:

  DB1:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: airline

  DB2:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: customers

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  C1:
    Type: AWS::Glue::Crawler
    Properties:
      Name: airline
      Role: !GetAtt Role.Arn
      DatabaseName: airline
      Targets:
        S3Targets:
          - Path: s3://airport-airline-operations-analytics-platform/silver/airline/

  C2:
    Type: AWS::Glue::Crawler
    Properties:
      Name: customers
      Role: !GetAtt Role.Arn
      DatabaseName: customers
      Targets:
        S3Targets:
          - Path: s3://airport-airline-operations-analytics-platform/silver/customers/
