AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Job Stack (Stable)

Parameters:
  ScriptBucket:
    Type: String
    Description: Existing S3 bucket where glue script is present

  ScriptKey:
    Type: String
    Description: Existing glue script key (example: scripts/glue_job.py)

  TempBucket:
    Type: String
    Description: Existing S3 bucket for Glue TempDir

  JobName:
    Type: String
    Default: FinalGlue

Resources:
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref JobName
      Role: !GetAtt GlueJobRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${ScriptBucket}/${ScriptKey}
      DefaultArguments:
        --job-language: python
        --TempDir: !Sub s3://${TempBucket}/glue-temp/
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 60
      MaxRetries: 0

Outputs:
  GlueJobName:
    Value: !Ref GlueJob
