AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Job for Gold Customers + Airline

Parameters:
  ScriptBucket:
    Type: String

  ScriptKey:
    Type: String

  JobName:
    Type: String
    Default: FinalGlue

Resources:

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  GlueTempBucket:
    Type: AWS::S3::Bucket

  FinalGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref JobName
      Role: !GetAtt GlueJobRole.Arn
      GlueVersion: "4.0"

      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${ScriptBucket}/${ScriptKey}

      DefaultArguments:
        --job-language: python
        --enable-continuous-cloudwatch-log: "true"
        --enable-metrics: "true"
        --TempDir: !Sub s3://${GlueTempBucket}/temp/

      WorkerType: G.1X
      NumberOfWorkers: 10
      Timeout: 120
      MaxRetries: 0

Outputs:
  GlueJobName:
    Value: !Ref FinalGlueJob
