AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Trigger Stack (Stable)

Parameters:
  LambdaName:
    Type: String

  CodeBucket:
    Type: String
    Description: Existing S3 bucket with lambda zip

  CodeKey:
    Type: String
    Description: Existing lambda zip key

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: GlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                  - glue:StartCrawler
                  - glue:GetCrawler
                Resource: "*"

  TriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Runtime: python3.9
      Handler: raw_lambda.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 900
      MemorySize: 256
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey

Outputs:
  LambdaArn:
    Value: !GetAtt TriggerLambda.Arn
