AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for Glue Trigger (SAFE VERSION)

Parameters:
  LambdaName:
    Type: String

  CodeBucket:
    Type: String

  CodeKey:
    Type: String


Resources:

# =========================
# IAM ROLE (no fixed name)
# =========================
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: GlueControlPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetCrawler
                  - glue:StartCrawler
                Resource: "*"


# =========================
# LAMBDA FUNCTION
# =========================
  GlueTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Runtime: python3.9
      Handler: lambda.lambda_handler   # ← file = lambda.py
      Timeout: 900
      MemorySize: 256
      Role: !GetAtt LambdaRole.Arn

      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey


Outputs:
  LambdaArn:
    Value: !GetAtt GlueTriggerLambda.Arn
